[project]
name = "caddyai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "ffmpeg>=1.4",
    "parakeet-mlx>=0.4.0",
]
